### ISSUE TITLE
go test fails with "panic: test timed out after 10m0s"

### ISSUE THREAD

**Issue by dims** [kubernetes/publishing-bot#220]
Example : https://github.com/kubernetes/kubernetes/issues/56876#issuecomment-595437372

```	
	?   	k8s.io/client-go/scale/scheme/appsv1beta1	[no test files]
	?   	k8s.io/client-go/scale/scheme/appsv1beta2	[no test files]
	?   	k8s.io/client-go/scale/scheme/autoscalingv1	[no test files]
	?   	k8s.io/client-go/scale/scheme/extensionsint	[no test files]
	?   	k8s.io/client-go/scale/scheme/extensionsv1beta1	[no test files]
	ok  	k8s.io/client-go/testing	(cached)
	?   	k8s.io/client-go/third_party/forked/golang/template	[no test files]
	ok  	k8s.io/client-go/tools/auth	(cached)
	ok  	k8s.io/client-go/tools/cache	16.299s
	ok  	k8s.io/client-go/tools/cache/testing	0.057s
	ok  	k8s.io/client-go/tools/clientcmd	(cached)
	ok  	k8s.io/client-go/tools/clientcmd/api	(cached)
	?   	k8s.io/client-go/tools/clientcmd/api/latest	[no test files]
	?   	k8s.io/client-go/tools/clientcmd/api/v1	[no test files]
	panic: test timed out after 10m0s

	goroutine 50 [running]:
	testing.(*M).startAlarm.func1()
		/go-workspace/go-1.13.4/src/testing/testing.go:1377 +0xdf
	created by time.goFunc
		/go-workspace/go-1.13.4/src/time/sleep.go:168 +0x44

	goroutine 1 [chan receive]:
	testing.(*T).Run(0xc0001d0200, 0x12257f1, 0x10, 0x12b20e8, 0x488b86)
		/go-workspace/go-1.13.4/src/testing/testing.go:961 +0x377
	testing.runTests.func1(0xc0001d0100)
		/go-workspace/go-1.13.4/src/testing/testing.go:1202 +0x78
	testing.tRunner(0xc0001d0100, 0xc0000d1dc0)
		/go-workspace/go-1.13.4/src/testing/testing.go:909 +0xc9
	testing.runTests(0xc0001b8580, 0x1c08040, 0x3, 0x3, 0x0)
		/go-workspace/go-1.13.4/src/testing/testing.go:1200 +0x2a7
	testing.(*M).Run(0xc0000e7e00, 0x0)
		/go-workspace/go-1.13.4/src/testing/testing.go:1117 +0x176
	main.main()
		_testmain.go:48 +0x135

	goroutine 6 [chan receive]:
	k8s.io/klog.(*loggingT).flushDaemon(0x1c18ea0)
		/go-workspace/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010 +0x8b
	created by k8s.io/klog.init.0
		/go-workspace/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0xd6

	goroutine 8 [chan receive]:
	k8s.io/client-go/tools/events.TestEventSeriesf(0xc0001d0200)
		/go-workspace/src/k8s.io/client-go/tools/events/eventseries_test.go:174 +0xd95
	testing.tRunner(0xc0001d0200, 0x12b20e8)
		/go-workspace/go-1.13.4/src/testing/testing.go:909 +0xc9
	created by testing.(*T).Run
		/go-workspace/go-1.13.4/src/testing/testing.go:960 +0x350

	goroutine 9 [chan receive]:
	k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc000210d80)
		/go-workspace/pkg/mod/k8s.io/apimachinery@v0.0.0-20200304180238-7c34f3d03f36/pkg/watch/mux.go:207 +0x66
	created by k8s.io/apimachinery/pkg/watch.NewBroadcaster
		/go-workspace/pkg/mod/k8s.io/apimachinery@v0.0.0-20200304180238-7c34f3d03f36/pkg/watch/mux.go:75 +0xcc

	goroutine 10 [chan send]:
	k8s.io/client-go/tools/events.TestEventSeriesf.func3(0xc000165900, 0xc0002d0000, 0x52, 0x60, 0x0, 0x0, 0x0)
		/go-workspace/src/k8s.io/client-go/tools/events/eventseries_test.go:155 +0x3e
	k8s.io/client-go/tools/events.(*testEventSeriesSink).Patch(0xc0001b85a0, 0xc000165900, 0xc0002d0000, 0x52, 0x60, 0x0, 0x0, 0x0)
		/go-workspace/src/k8s.io/client-go/tools/events/eventseries_test.go:62 +0x5b
	k8s.io/client-go/tools/events.recordEvent(0x13c12e0, 0xc0001b85a0, 0xc000165900, 0x0, 0x0)
		/go-workspace/src/k8s.io/client-go/tools/events/event_broadcaster.go:216 +0x622
	k8s.io/client-go/tools/events.(*eventBroadcasterImpl).refreshExistingEventSeries(0xc000230390)
		/go-workspace/src/k8s.io/client-go/tools/events/event_broadcaster.go:116 +0x13c
	k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartRecordingToSink.func1()
		/go-workspace/src/k8s.io/client-go/tools/events/event_broadcaster.go:298 +0x2a
	k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000167140)
		/go-workspace/pkg/mod/k8s.io/apimachinery@v0.0.0-20200304180238-7c34f3d03f36/pkg/util/wait/wait.go:155 +0x5e
	k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000167140, 0x1396e00, 0xc000276000, 0xc0000fa001, 0xc000090720)
		/go-workspace/pkg/mod/k8s.io/apimachinery@v0.0.0-20200304180238-7c34f3d03f36/pkg/util/wait/wait.go:156 +0xa3
	k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000167140, 0x1a3185c5000, 0x0, 0x1, 0xc000090720)
		/go-workspace/pkg/mod/k8s.io/apimachinery@v0.0.0-20200304180238-7c34f3d03f36/pkg/util/wait/wait.go:133 +0xe2
	k8s.io/apimachinery/pkg/util/wait.Until(0xc000167140, 0x1a3185c5000, 0xc000090720)
		/go-workspace/pkg/mod/k8s.io/apimachinery@v0.0.0-20200304180238-7c34f3d03f36/pkg/util/wait/wait.go:90 +0x4d
	created by k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartRecordingToSink
		/go-workspace/src/k8s.io/client-go/tools/events/event_broadcaster.go:297 +0x8c

	goroutine 11 [semacquire]:
	sync.runtime_SemacquireMutex(0xc00023039c, 0xc00006eb00, 0x1)
		/go-workspace/go-1.13.4/src/runtime/sema.go:71 +0x47
	sync.(*Mutex).lockSlow(0xc000230398)
		/go-workspace/go-1.13.4/src/sync/mutex.go:138 +0xfc
	sync.(*Mutex).Lock(...)
		/go-workspace/go-1.13.4/src/sync/mutex.go:81
	k8s.io/client-go/tools/events.(*eventBroadcasterImpl).finishSeries(0xc000230390)
		/go-workspace/src/k8s.io/client-go/tools/events/event_broadcaster.go:130 +0x32f
	k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartRecordingToSink.func2()
		/go-workspace/src/k8s.io/client-go/tools/events/event_broadcaster.go:301 +0x2a
	k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000167150)
		/go-workspace/pkg/mod/k8s.io/apimachinery@v0.0.0-20200304180238-7c34f3d03f36/pkg/util/wait/wait.go:155 +0x5e
	k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000167150, 0x1396e00, 0xc0002303c0, 0xc000010601, 0xc000090720)
		/go-workspace/pkg/mod/k8s.io/apimachinery@v0.0.0-20200304180238-7c34f3d03f36/pkg/util/wait/wait.go:156 +0xa3
	k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000167150, 0x53d1ac1000, 0x0, 0x1, 0xc000090720)
		/go-workspace/pkg/mod/k8s.io/apimachinery@v0.0.0-20200304180238-7c34f3d03f36/pkg/util/wait/wait.go:133 +0xe2
	k8s.io/apimachinery/pkg/util/wait.Until(0xc000167150, 0x53d1ac1000, 0xc000090720)
		/go-workspace/pkg/mod/k8s.io/apimachinery@v0.0.0-20200304180238-7c34f3d03f36/pkg/util/wait/wait.go:90 +0x4d
	created by k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartRecordingToSink
		/go-workspace/src/k8s.io/client-go/tools/events/event_broadcaster.go:300 +0xf7

	goroutine 12 [chan receive]:
	k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartEventWatcher.func1(0x13a0280, 0xc0002303f0, 0xc000167160)
		/go-workspace/src/k8s.io/client-go/tools/events/event_broadcaster.go:285 +0xce
	created by k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartEventWatcher
		/go-workspace/src/k8s.io/client-go/tools/events/event_broadcaster.go:282 +0x72

	goroutine 13 [chan receive]:
	k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartRecordingToSink.func4(0xc000090720, 0xc0001b8620)
		/go-workspace/src/k8s.io/client-go/tools/events/event_broadcaster.go:313 +0x34
	created by k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartRecordingToSink
		/go-workspace/src/k8s.io/client-go/tools/events/event_broadcaster.go:312 +0x162

	goroutine 34 [semacquire]:
	sync.runtime_SemacquireMutex(0xc00023039c, 0x121d400, 0x1)
		/go-workspace/go-1.13.4/src/runtime/sema.go:71 +0x47
	sync.(*Mutex).lockSlow(0xc000230398)
		/go-workspace/go-1.13.4/src/sync/mutex.go:138 +0xfc
	sync.(*Mutex).Lock(...)
		/go-workspace/go-1.13.4/src/sync/mutex.go:81
	k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink.func1(0xc000230390, 0xc000274000, 0x13cf680, 0x1c35f30)
		/go-workspace/src/k8s.io/client-go/tools/events/event_broadcaster.go:181 +0x27d
	created by k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink
		/go-workspace/src/k8s.io/client-go/tools/events/event_broadcaster.go:156 +0x68

	goroutine 19 [semacquire]:
	sync.runtime_SemacquireMutex(0xc00023039c, 0x0, 0x1)
		/go-workspace/go-1.13.4/src/runtime/sema.go:71 +0x47
	sync.(*Mutex).lockSlow(0xc000230398)
		/go-workspace/go-1.13.4/src/sync/mutex.go:138 +0xfc
	sync.(*Mutex).Lock(...)
		/go-workspace/go-1.13.4/src/sync/mutex.go:81
	k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink.func1.1(0xc000230390, 0xc000278280, 0x13cf680, 0x1c35f30, 0x0)
		/go-workspace/src/k8s.io/client-go/tools/events/event_broadcaster.go:158 +0x402
	k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink.func1(0xc000230390, 0xc000278280, 0x13cf680, 0x1c35f30)
		/go-workspace/src/k8s.io/client-go/tools/events/event_broadcaster.go:176 +0x6a
	created by k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink
		/go-workspace/src/k8s.io/client-go/tools/events/event_broadcaster.go:156 +0x68
	FAIL	k8s.io/client-go/tools/events	600.020s
	ok  	k8s.io/client-go/tools/leaderelection	0.073s
	?   	k8s.io/client-go/tools/leaderelection/resourcelock	[no test files]
	?   	k8s.io/client-go/tools/metrics	[no test files]
	ok  	k8s.io/client-go/tools/pager	(cached)
	ok  	k8s.io/client-go/tools/portforward	0.013s
	ok  	k8s.io/client-go/tools/record	0.148s
	?   	k8s.io/client-go/tools/record/util	[no test files]
	ok  	k8s.io/client-go/tools/reference	0.041s
	ok  	k8s.io/client-go/tools/remotecommand	0.013s
	ok  	k8s.io/client-go/tools/watch	12.281s
	ok  	k8s.io/client-go/transport	0.017s
	?   	k8s.io/client-go/transport/spdy	[no test files]
	ok  	k8s.io/client-go/util/cert	0.022s
	ok  	k8s.io/client-go/util/certificate	0.054s
	ok  	k8s.io/client-go/util/certificate/csr	0.123s
	ok  	k8s.io/client-go/util/connrotation	(cached)
	?   	k8s.io/client-go/util/exec	[no test files]
	ok  	k8s.io/client-go/util/flowcontrol	(cached)
	?   	k8s.io/client-go/util/homedir	[no test files]
	ok  	k8s.io/client-go/util/jsonpath	(cached)
	ok  	k8s.io/client-go/util/keyutil	(cached)
	ok  	k8s.io/client-go/util/retry	(cached)
	ok  	k8s.io/client-go/util/testing	(cached)
	ok  	k8s.io/client-go/util/workqueue	(cached)
	FAIL
[05 Mar 20 20:43 UTC]: exit status 1
    	+ go build ./...
    	+ go test ./...

[05 Mar 20 20:43 UTC]: exit status 1```
```

**Comment by dims** [comment]
per @liggitt `there's a hang in that package's unit tests`
